version: '3'
services:
  api:
    image: node:14
    ports :
      - "80:80"
    volumes:
      - ./api:/api
    depends_on:
      - database
    working_dir: /api
    command: npm start

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: api_database
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    ports:
      - "8888:80"
    environment:
      - PMA_ARBITRARY=1